import pandas as pd
from tableone import TableOne

dataset_filename = 'NhanesPrepandemicAll.csv'

df = pd.read_csv(f'data/processed/{dataset_filename}').drop('Unnamed: 0', axis=1)

TARGETS = ["isAtRiskMASH35","isAtRiskMASH67"]

cols = [
    "EVER TOLD YOU HAD HIGH BLOOD PRESSURE",
    "TOLD HAD HIGH BLOOD PRESSURE - 2+ TIMES",
    "AGE TOLD HAD HYPERTENSION",
    "TAKING PRESCRIPTION FOR HYPERTENSION",
    "NOW TAKING PRESCRIBED MEDICINE FOR HBP",
    "DOCTOR TOLD YOU - HIGH CHOLESTEROL LEVEL",
    "TOLD TO TAKE PRESCRIPTN FOR CHOLESTEROL",
    "DOCTOR TOLD YOU HAVE DIABETES",
    "AGE WHEN FIRST TOLD YOU HAD DIABETES",
    "EVER TOLD YOU HAVE PREDIABETES",
    "HAD BLOOD TESTED PAST THREE YEARS",
    "TAKING INSULIN NOW",
    "HOW LONG TAKING INSULIN",
    "TAKE DIABETIC PILLS TO LOWER BLOOD SUGAR",
    "DOCTOR EVER SAID YOU WERE OVERWEIGHT",
    "EVER TOLD HAD CONGESTIVE HEART FAILURE",
    "EVER TOLD YOU HAD CORONARY HEART DISEASE",
    "EVER TOLD YOU HAD ANGINA/ANGINA PECTORIS",
    "EVER TOLD YOU HAD HEART ATTACK",
    "EVER TOLD YOU HAD A STROKE",
    "DO YOU STILL HAVE A LIVER CONDITION",
    "LIVER CONDITION: FATTY LIVER",
    "LIVER CONDITION: LIVER FIBROSIS",
    "LIVER CONDITION: LIVER CIRRHOSIS",
    "LIVER CONDITION: VIRAL HEPATITIS",
    "LIVER CONDITION: AUTOIMMUNE HEPATITIS",
    "LIVER CONDITION: OTHER LIVER DISEASE",
    "EVER TOLD YOU HAD CANCER OR MALIGNANCY",
    "DOCTOR TOLD YOU TO CONTROL/LOSE WEIGHT",
    "DOCTOR TOLD YOU TO EXERCISE",
    "DOCTOR TOLD YOU TO REDUCE SALT IN DIET",
    "DOCTOR TOLD YOU TO REDUCE FAT/CALORIES",
    "ARE YOU NOW CONTROLLING OR LOSING WEIGHT",
    "ARE YOU NOW INCREASING EXERCISE",
    "ARE YOU NOW REDUCING SALT IN DIET",
    "ARE YOU NOW REDUCING FAT IN DIET",
    "GENDER",
    "AGE IN YEARS AT SCREENING",
    "RACE/HISPANIC ORIGIN",
    "RACE/HISPANIC ORIGIN W/ NH ASIAN",
    "COUNTRY OF BIRTH",
    "LENGTH OF TIME IN US",
    "EDUCATION LEVEL - ADULTS 20+",
    "MARITAL STATUS",
    "PREGNANCY STATUS AT EXAM",
    "RATIO OF FAMILY INCOME TO POVERTY",
    "BODY MASS INDEX (KG/M**2)",
    "WAIST CIRCUMFERENCE (CM)",
    "TOTAL SPINE BMD",
    "TOTAL SPINE BMC",
    "TOTAL SPINE AREA",
    "CALCULATED K FOR SPINE",
    "CALCULATED DO FOR SPINE",
    "ALBUMIN, URINE (UG/ML)",
    "CREATININE, URINE (MG/DL)",
    "ALBUMIN CREATININE RATIO (MG/G)",
    "DIRECT HDL-CHOLESTEROL (MG/DL)",
    "TRIGLYCERIDE (MG/DL)",
    "LDL-CHOLESTEROL, FRIEDEWALD (MG/DL)",
    "LDL-CHOLESTEROL, MARTIN-HOPKINS (MG/DL)",
    "LDL-CHOLESTEROL, NIH EQUATION 2 (MG/DL)",
    "TOTAL CHOLESTEROL (MG/DL)",
    "WHITE BLOOD CELL COUNT (1000 CELLS/UL)",
    "LYMPHOCYTE PERCENT (%)",
    "MONOCYTE PERCENT (%)",
    "SEGMENTED NEUTROPHILS PERCENT (%)",
    "EOSINOPHILS PERCENT (%)",
    "BASOPHILS PERCENT (%)",
    "LYMPHOCYTE NUMBER (1000 CELLS/UL)",
    "MONOCYTE NUMBER (1000 CELLS/UL)",
    "SEGMENTED NEUTROPHILS NUM (1000 CELL/UL)",
    "EOSINOPHILS NUMBER (1000 CELLS/UL)",
    "BASOPHILS NUMBER (1000 CELLS/UL)",
    "RED BLOOD CELL COUNT (MILLION CELLS/UL)",
    "HEMOGLOBIN (G/DL)",
    "HEMATOCRIT (%)",
    "MEAN CELL VOLUME (FL)",
    "MEAN CELL HGB CONC. (G/DL)",
    "MEAN CELL HEMOGLOBIN (PG)",
    "RED CELL DISTRIBUTION WIDTH (%)",
    "PLATELET COUNT (1000 CELLS/UL)",
    "MEAN PLATELET VOLUME (FL)",
    "NUCLEATED RED BLOOD CELLS",
    "FERRITIN (NG/ML)",
    "RBC FOLATE (NG/ML)",
    "GLYCOHEMOGLOBIN (%)",
    "HEPATITIS A ANTIBODY",
    "HEPATITIS D ANTIBODY (ANTI-HDV)",
    "HEPATITIS E IGG (ANTI-HEV)",
    "HEPATITIS E IGM (ANTI-HEV)",
    "HS C-REACTIVE PROTEIN (MG/L)",
    "INSULIN (μU/ML)",
    "IRON FROZEN, SERUM (UG/DL)",
    "UIBC, SERUM (UG/DL)",
    "TOTAL IRON BINDING CAPACITY TIBC (UG/DL)",
    "TRANSFERRIN SATURATION (%)",
    "FASTING GLUCOSE (MG/DL)",
    "ALANINE AMINOTRANSFERASE (ALT) (U/L)",
    "ALBUMIN, REFRIGERATED SERUM (G/DL)",
    "ALKALINE PHOSPHATASE (ALP) (IU/L)",
    "BICARBONATE (MMOL/L)",
    "BLOOD UREA NITROGEN (MG/DL)",
    "CHLORIDE (MMOL/L)",
    "CREATINE PHOSPHOKINASE (CPK) (IU/L)",
    "CREATININE, REFRIGERATED SERUM (MG/DL)",
    "GLOBULIN (G/DL)",
    "GLUCOSE, REFRIGERATED SERUM (MG/DL)",
    "GAMMA GLUTAMYL TRANSFERASE (GGT) (IU/L)",
    "IRON, REFRIGERATED SERUM (UG/DL)",
    "LACTATE DEHYDROGENASE (LDH) (IU/L)",
    "OSMOLALITY (MMOL/KG)",
    "PHOSPHORUS (MG/DL)",
    "POTASSIUM (MMOL/L)",
    "SODIUM (MMOL/L)",
    "TOTAL BILIRUBIN (MG/DL)",
    "TOTAL CALCIUM (MG/DL)",
    "CHOLESTEROL, REFRIGERATED SERUM (MG/DL)",
    "TOTAL PROTEIN (G/DL)",
    "TRIGLYCERIDES, REFRIG SERUM (MG/DL)",
    "URIC ACID (MG/DL)",
    "TRANSFERRIN RECEPTOR (MG/L)",
    "URINE PREGNANCY RESULT",
    "Alcohol_g_per_day",
    "HOMAIR",
    "isDM"
]

categorical = ["EVER TOLD YOU HAD HIGH BLOOD PRESSURE",
    "TOLD HAD HIGH BLOOD PRESSURE - 2+ TIMES",
    "TAKING PRESCRIPTION FOR HYPERTENSION",
    "NOW TAKING PRESCRIBED MEDICINE FOR HBP",
    "DOCTOR TOLD YOU - HIGH CHOLESTEROL LEVEL",
    "TOLD TO TAKE PRESCRIPTN FOR CHOLESTEROL",
    "DOCTOR TOLD YOU HAVE DIABETES",
    "EVER TOLD YOU HAVE PREDIABETES",
    "HAD BLOOD TESTED PAST THREE YEARS",
    "TAKING INSULIN NOW",
    "TAKE DIABETIC PILLS TO LOWER BLOOD SUGAR",
    "DOCTOR EVER SAID YOU WERE OVERWEIGHT",
    "EVER TOLD HAD CONGESTIVE HEART FAILURE",
    "EVER TOLD YOU HAD CORONARY HEART DISEASE",
    "EVER TOLD YOU HAD ANGINA/ANGINA PECTORIS",
    "EVER TOLD YOU HAD HEART ATTACK",
    "EVER TOLD YOU HAD A STROKE",
    "DO YOU STILL HAVE A LIVER CONDITION",
    "LIVER CONDITION: FATTY LIVER",
    "LIVER CONDITION: LIVER FIBROSIS",
    "LIVER CONDITION: LIVER CIRRHOSIS",
    "LIVER CONDITION: VIRAL HEPATITIS",
    "LIVER CONDITION: AUTOIMMUNE HEPATITIS",
    "LIVER CONDITION: OTHER LIVER DISEASE",
    "EVER TOLD YOU HAD CANCER OR MALIGNANCY",
    "DOCTOR TOLD YOU TO CONTROL/LOSE WEIGHT",
    "DOCTOR TOLD YOU TO EXERCISE",
    "DOCTOR TOLD YOU TO REDUCE SALT IN DIET",
    "DOCTOR TOLD YOU TO REDUCE FAT/CALORIES",
    "ARE YOU NOW CONTROLLING OR LOSING WEIGHT",
    "ARE YOU NOW INCREASING EXERCISE",
    "ARE YOU NOW REDUCING SALT IN DIET",
    "ARE YOU NOW REDUCING FAT IN DIET",
    "GENDER",
    "RACE/HISPANIC ORIGIN",
    "RACE/HISPANIC ORIGIN W/ NH ASIAN",
    "COUNTRY OF BIRTH",
    "EDUCATION LEVEL - ADULTS 20+",
    "MARITAL STATUS",
    "PREGNANCY STATUS AT EXAM",
    "isDM",
    "URINE PREGNANCY RESULT"]

continuous = [col for col in cols if col not in categorical]

for target in TARGETS:
    print(f"Table for {target}:")
    table = TableOne(df, columns=cols + [target], categorical=categorical, groupby=target, pval=True, nonnormal=continuous)
    table.to_excel(f"{target}_table.xlsx")












# Imputed subset
from sklearn.impute import KNNImputer
df = pd.read_csv('data/processed/NhanesPrepandemicAllWithAST.csv').drop('Unnamed: 0', axis=1)

# Assuming these are the columns you're interested in
cols = ['AGE IN YEARS AT SCREENING', 'GENDER', 'RACE/HISPANIC ORIGIN W/ NH ASIAN', 'isDM', 'BODY MASS INDEX (KG/M**2)', 'WAIST CIRCUMFERENCE (CM)', 'ASPARTATE AMINOTRANSFERASE (AST) (U/L)', 'ALANINE AMINOTRANSFERASE (ALT) (U/L)', 'GAMMA GLUTAMYL TRANSFERASE (GGT) (IU/L)', 'ALBUMIN, REFRIGERATED SERUM (G/DL)', 'PLATELET COUNT (1000 CELLS/UL)', 'GLYCOHEMOGLOBIN (%)', 'FASTING GLUCOSE (MG/DL)', 'INSULIN (μU/ML)', 'DIRECT HDL-CHOLESTEROL (MG/DL)', 'HOMAIR']
categorical = ["GENDER", "RACE/HISPANIC ORIGIN W/ NH ASIAN", "isDM"]
continuous = [col for col in cols if col not in categorical]


# Usage example
TARGET = "isAtRiskMASH35"  # Example for one target

df = df[cols + [TARGET]]

# Impute
imputer = KNNImputer(n_neighbors=5)
df = pd.DataFrame(imputer.fit_transform(df), columns = df.columns)

for col in categorical:
    df[col] = df[col].astype('category').cat.codes


table = TableOne(df, columns=cols + [TARGET], categorical=categorical, groupby=TARGET, pval=False, nonnormal=continuous)
table.to_excel(f"{TARGET}_imputed_table.xlsx")
